### ISSUE TITLE
Potential conflict of -J option

### ISSUE THREAD

**Issue by aminophen** [vtex-soft/texlive.xdvipsk#1]
JFYI:

Tom is working on improving searchability of Type 3 bitmap fonts on dvips. He gave a talk at TUG 2019 and a preprint of TUGboat is also available:

- Searchable PDFs with Type 3 bitmap fonts https://tug.org/tug2019/program.html

According to his commits (https://github.com/TeX-Live/texlive-source/compare/trunk...rokicki:trunk), a new option -J is introduced:

```
-J*  Good encodings for bitmap fonts
```

It seems that xdvipsk has already an option -J:

```
-J*  Download OpenType fonts partially
```

If you have any plan to update on 2020, some confusion may occur.

**Comment by aminophen** [comment]
I should have notified to @rokicki too.

Sigitas and his colleague at VTeX gave a talk on TUG/BachoTeX 2017:

- Xdvipsk: dvips ready for OpenType fonts and more image types http://www.gust.org.pl/bachotex/2017-en/program

The article is also available as TUGboat, Volume 38 (2017), No. 2, pp.197–201.

**Comment by rokicki** [comment]
I can use a non-letter option (/ or some such) but I'll need to ensure it works in config files.  Or do you have an alternate suggestion?  I hate to use slashes because people get confused between forward and back slashes.  But so few people will probably use this option that that is probably okay.

**Comment by aminophen** [comment]
dvips already has some long options --noptex and --noomega, so choosing such long names for rarely used options can be fine. (I don't know whether those existing long options works in config files, sorry)

**Comment by rokicki** [comment]
I don't think those long options work in config files, and the long options are a bit of a hack.  I'd prefer to keep the rather old-fashioned short options even if this means leveraging non-alphabetic characters.  But that's just me.

**Comment by aminophen** [comment]
If you don't have any plan to integrate xdvipsk changes into main dvips, no need to worry. I think Tom would be the best person for deciding things on dvips. Obviously xdvipsk has different name from dvips, so I can just ignore it. I raised this just for information.
