### ISSUE TITLE
Should this be made part of TeXLive dvips?

### ISSUE THREAD

**Issue by rokicki** [vtex-soft/texlive.xdvipsk#2]
So I'm trying to think if these changes should be made part of standard dvips.  Please pardon me for adding the issue here rather than on the TeXLive repository.

1.  Does this impact the TeXLive build process?  Are the dependencies generally available
    and portable?

2.  Do these changes, or their dependencies, introduce licensing issues?

3.  Are the changes in demand at all?  Has anyone requested such changes?

4.  If these changes leverage the dvips workflow, does the additional support (separately for graphics and fonts) translate over equivalently to the pdflatex/luatex world?  If there is separate but incompatible support in pdflatex/luatex, can these be brought into alignment?

5.  Do the authors of these changes feel like they should be part of mainline dvips?  If so, do they have any reasons why that they can enumerate?

My temptation is to leave dvips alone as much as possible but I don't want to dismiss obviously useful changes that don't have much impact on current usage.

**Comment by sigto** [comment]
> 1. Does this impact the TeXLive build process? Are the dependencies generally available
> and portable?

It adds additional dependencies: JPEG, TIFF, MUPDF libraries and xdvipsk, make2unc programs. They should be generally available and portable.

> 2. Do these changes, or their dependencies, introduce licensing issues?

Guess no.

> 3. Are the changes in demand at all? Has anyone requested such changes?

VTeX needs xdvipsk functionality, for others it is unclear. Maybe it can be asked in some common TeX community forums? 

> 4. If these changes leverage the dvips workflow, does the additional support (separately for 
graphics and fonts) translate over equivalently to the pdflatex/luatex world? If there is separate but incompatible support in pdflatex/luatex, can these be brought into alignment?

 These changes just extend luatex support for dvi backend. It is unusable with pdflatex except the standard dvips behaviour.

> 5. Do the authors of these changes feel like they should be part of mainline dvips? If so, do they have any reasons why that they can enumerate?

The authors of these changes are ready to provide any support to implement xdvipsk additional features in dvips and keep it up to date to the actual dvips maintainers.
